name: Build

# Triggers the pipeline on any git push or pull request being created.
on: [push, pull_request]

jobs:
  build:
    # Run on Ubuntu
    runs-on: ubuntu-latest

    steps:
    # Pull the code.
    - name: Checkout Repositories and Submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    # Set up .NET 5.
    - name: Set Up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    # Set up NPM (for LCOV merging, coveralls.io does not accept JSON inputs and MergeWith for dotnet test doesn't work for lcov).
    - name: Set Up Yarn
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install
    # Set up LCOV merge tool.
    - name: Set Up LCOV merge tool
      run: sudo yarn add lcov-result-merger
    # Run the tests with code coverage.
    - name: Test with Code Coverage
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov /p:Exclude="[*.Test]*"
    # Merge the LCOV files.
    - name: Merge LCOV files
      run: ./node_modules/.bin/lcov-result-merger '*/TestResults/coverage.info' 'coverage.info'
    # Upload the code coverage report.
    - name: Publish coverage report to coveralls.io   
      uses: coverallsapp/github-action@master   
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        path-to-lcov: coverage.info 